#!/bin/sh
## This script updates your qutebrowser greasemonkey scripts, and creates backup of old ones
#set -x

# Comment this out if don't want notification
notify=1

if [ $notify = 1 ]; then
  notify-send -i "/usr/share/icons/Papirus/16x16/categories/qutebrowser.svg" "Qutebrowser: Greasemonkey Update" "Proceeding..."
fi

greasemonkey_dir=${XDG_CONFIG_HOME:-$HOME/.config}/qutebrowser/greasemonkey
greasemonkey_bak=${XDG_CONFIG_HOME:-$HOME/.config}/qutebrowser/greasemonkey-old

mkdir -p "$greasemonkey_bak"

compare_versions() {
  vold=$(grep '@version' "$file" | awk '{print $3}')
  vnew=$(grep '@version' "$file.new" | awk '{print $3}')

  if echo "$vold" | grep "-" || echo "$vnew" | grep "-"; then
    # probably date versioning
    vnew=$(echo $vnew | sed -e 's/-/*1000+/' -e 's/-/*100+/')
    vnew=$((vnew))
    vold=$(echo $vold | sed -e 's/-/*1000+/' -e 's/-/*100+/')
    vold=$((vold))
    if [ "$vold" -lt "$vnew" ]; then
      return 0
    fi
  elif echo "$vold" | grep "[a-zA-Z]" || echo "$vnew" | grep "[a-zA-Z]"; then
    # TODO:
    # probably commit versioning
    :
  else
    set -- $(echo $vnew | tr '.' ' ')
    for i in $(echo $vold | tr '.' ' '); do
      if [ "$i" -lt "$1" ]; then
        return 0
      fi
      shift
    done
  fi

  return 1
}

updated=0
for file in $greasemonkey_dir/*; do
  if ! grep '@downloadURL' "$file"; then
    continue
  fi

  grep '@downloadURL' "$file" | curl "$(awk '{print $3}')" -o "$file.new"
  if compare_versions; then
    mv "$file" "$greasemonkey_bak/$(basename $file).old"
    mv "$file.new" "$file"
    if [ $notify = 1 ]; then
      notify-send -i "/usr/share/icons/Papirus/16x16/categories/qutebrowser.svg" "Qutebrowser: Greasemonkey Update" "$file"
    fi
    updated=$((updated + 1))
  else
    rm "$file.new"
  fi
done

if [ $notify = 1 ] && [ $updated = 0 ]; then
  notify-send -i "/usr/share/icons/Papirus/16x16/categories/qutebrowser.svg" "Qutebrowser: Greasemonkey Update" "Nothing to update..."
fi
