#!/bin/bash
#set -x

wids=$(bspc query -N -n .local.hidden)

for wid in $wids; do
  wclass=$(xdotool getwindowclassname "$wid")
  wname=$(xdotool getwindowname "$wid")
  #if [ -n "$wclass" ]; then
  if [ -n "$wclass" ] && [ -n "$wname" ]; then
    warr+=("$wclass - $wname")
    widarr+=("#$wid")
  fi
done

#for i in "${!warr[@]}"; do
#  warr_rofi+="$(printf "%s\twid:%s\n" "${warr[i]}" "${widarr[i]}")"
#done
warr_rofi=$(paste <(printf "%s\n" "${warr[@]}") <(printf "\twid: %s\n" "${widarr[@]}"))

wids=''
if command -v skippy-xd >/dev/null; then
  wids=$(skippy-xd --expose --multi-select --desktop -1 --wm-status minimized)
elif command -v rofi >/dev/null; then
  choice=$(rofi -dmenu -p "Unhide Window" <<<"$warr_rofi") #-normal-window <<< "$warr_rofi")
  wids=$(echo "$choice" | awk -F"wid: #" '{print $2}')
else
  echo "error missing command"
  exit 1
fi

for wid in $wids; do
  # don't focus
  bspc node "$wid" -g hidden=off #focus=on
done
