#!/usr/bin/env bash

## Author  : Aditya Shakya (adi1090x)
## Github  : @adi1090x
#
## Applets : Power Menu

# Current Theme
theme="$XDG_CONFIG_HOME/rofi/applet.rasi"
if [ "$1" ]; then
  theme="$1"
fi

# Theme Elements
prompt="$(hostname)"
mesg="Uptime : $(uptime -p | sed -e 's/up //g')"

list_col='1'
list_row='6'

# Options
layout=$(cat ${theme} | grep 'USE_ICON' | cut -d'=' -f2)
if [[ "$layout" == 'NO' ]]; then
  option_1=" Lock"
  option_2=" Logout"
  option_3=" Suspend"
  option_4=" Hibernate"
  option_5=" Reboot"
  option_6=" Shutdown"
  yes=' Yes'
  no=' No'
else
  option_1=""
  option_2=""
  option_3=""
  option_4=""
  option_5=""
  option_6=""
  yes=''
  no=''
fi

# Rofi CMD
rofi_cmd() {
  rofi -theme-str "listview {columns: $list_col; lines: $list_row;}" \
    -theme-str 'textbox-prompt-colon {str: "";}' \
    -dmenu \
    -p "$prompt" \
    -mesg "$mesg" \
    -markup-rows \
    -theme ${theme}
  #-normal-window
}

# Pass variables to rofi dmenu
run_rofi() {
  echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Confirmation CMD
confirm_cmd() {
  rofi -theme-str 'window {location: center; anchor: center; fullscreen: false; width: 350px;}' \
    -theme-str 'mainbox {orientation: vertical; children: [ "message", "listview" ];}' \
    -theme-str 'listview {columns: 2; lines: 1;}' \
    -theme-str 'element-text {horizontal-align: 0.5;}' \
    -theme-str 'textbox {horizontal-align: 0.5;}' \
    -dmenu \
    -p 'Confirmation' \
    -mesg 'Are you Sure?' \
    -theme ${theme}

}

# Ask for confirmation
confirm_exit() {
  echo -e "$yes\n$no" | confirm_cmd
}

# Confirm and execute
confirm_run() {
  selected="$(confirm_exit)"
  if [[ "$selected" == "$yes" ]]; then
    ${1} && ${2} && ${3}
  else
    exit
  fi
}

# Execute Command
run_cmd() {
  if [[ "$1" == '--opt1' ]]; then
    if [ $XDG_SESSION_TYPE = x11 ]; then
      bslock &
    else
      #waylock &

      #grim ~/Pictures/screenlock.png
      #videoglitch -j 50 ~/Pictures/screenlock.png ~/Pictures/screenlock.png

      swaylock \
        --clock \
        --indicator \
        --indicator-radius 100 \
        --indicator-thickness 7 \
        --ring-color bb00cc \
        --key-hl-color 880033 \
        --line-color 00000000 \
        --inside-color 00000088 \
        --separator-color 00000000 \
        --grace 2 \
        --fade-in 0.2 \
        --effect-pixelate 8 \
        --effect-vignette 0.2:0.2 \
        --screenshots
      #--effect-blur 7x5 \
      #--image ~/Pictures/screenlock.png
    fi
  elif [[ "$1" == '--opt2' ]]; then
    confirm_run 'kill -9 -1'
  elif [[ "$1" == '--opt3' ]]; then
    confirm_run 'mpc -q pause' 'amixer set Master mute' 'systemctl suspend'
  elif [[ "$1" == '--opt4' ]]; then
    confirm_run 'systemctl hibernate'
  elif [[ "$1" == '--opt5' ]]; then
    confirm_run 'systemctl reboot'
  elif [[ "$1" == '--opt6' ]]; then
    confirm_run 'systemctl poweroff'
  fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
$option_1)
  run_cmd --opt1
  ;;
$option_2)
  run_cmd --opt2
  ;;
$option_3)
  run_cmd --opt3
  ;;
$option_4)
  run_cmd --opt4
  ;;
$option_5)
  run_cmd --opt5
  ;;
$option_6)
  run_cmd --opt6
  ;;
esac
