#! /bin/sh

#sxhkd=/usr/local/bin/sxhkd
#bspc=/usr/local/bin/bspc

#pgrep -x sxhkd  -c /etc/X11/bspwm/sxhkdrc> /dev/null || sxhkd -c /etc/X11/bspwm/sxhkdrc &
#sxhkd -c /etc/X11/bspwm/sxhkdrc &
export CM_LAUNCHER=rofi-script
export XDG_CURRENT_DESKTOP=bspwm
export OPACITY_VALUE=1.0

if [ $(bspc query -M --names | wc -l) -gt 1 ]; then
  bspc monitor DP-1 -d I II III IV V VI VII VIII IX X
  #bspc monitor DP-1 -d   II III IV V VI      
  #bspc monitor DP-1 -d  II III IV V VI VII   
  bspc monitor eDP-1 -r 
  xrandr --output eDP-1 --off
  bspc remove_unplugged_monitors
  bspc remove_disabled_monitors
else
  bspc monitor -d I II III IV V VI VII VIII IX X
  #bspc monitor -d   II III IV V VI      
  #bspc monitor -d  II III IV V VI VII   
   
fi

feh --bg-fill --no-fehbg --xinerama-index 0 --randomize ~/Pictures/wallpapers/arch1*

# probably unneeded
#dbus-update-activation-environment --all
# for protonvpn
killall "nm-applet"
nm-applet &

killall "autohide-tdrop"
killall "sxhkd"
sxhkd &
killall "clipmenu"
clipmenud &
killall "polybar"
polybar &
xinput set-prop 'Logitech M705' 'libinput Accel Speed' -0.7
killall "picom"
picom &
xset b off
#xset s 1200 30
#xss-lock -n $XDG_CONFIG_HOME/bslock/dim-screen.sh -- bslock &
killall "kdeconnect-indicator"
kdeconnect-indicator &
#/home/daru/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js &


bspc config border_width        3
bspc config focused_border_color "#6181FF" 
#bspc config normal_border_color "#FFFFFF"
#
#outdated in 0.9.1 and up
#bspc config urgent_border_color "#ff0000#" 
#
./border_color.sh
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config ignore_ewmh_focus	 true

# mouse actions
# works by default
#bspc config pointer_modifier super
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action3 resize_corner
#bspc config click_to_focus true

# this was because regex doesn't exist in bspwm and I wanted to catch window names
# relative to their versions e.g. foo 1.6 | foo 2.3
#minecraft=$(xprop -root _NET_CLIENT_LIST | pcreerep -o1 '# (.*)' | sed 's/, /\n/g' | xargs -I{} -n1 xprop -id {} WM_NAME | grep -o '"Minecraft.*"' | sed -n '2p')
#tlminecraft=$(xprop -root _NET_CLIENT_LIST | pcregrep -o1 '# (.*)' | sed 's/, /\n/g' | xargs -I{} -n1 xprop -id {} WM_NAME | grep -o '"TL.*"' | sed -n '2p')

bspc rule -r "*"
bspc rule -a "*" rectangle=900x550+0+0 center=on follow=on
#bspc rule -a tdropkitty state=floating layer=above center=on
bspc rule -a mpv state=floating layer=above center=off rectangle=550x350+1340+660
bspc rule -a "firefoxdeveloperedition" desktop=focused focus=on
bspc rule -a Zathura state=tiled
bspc rule -a "tdrop-kitty" locked=on
bspc rule -a "Show Me The Key" manage=off
#bspc rule -a Screenkey manage=off

# workspace/desktop assigment
bspc rule -a "Gimp" desktop='^5' follow=on
bspc rule -a "lmms" desktop='^6' focus=on follow=on
bspc rule -a "Carla2" desktop='^7' focus=on follow=on
bspc rule -a "Guitarix" desktop='^8' focus=on follow=on
bspc rule -a "obs" desktop='^9' focus=on follow=on
minecraft="Minecraft 1.12.2"
#minecraft="Minecraft* 1.19.2"
bspc rule -a "$minecraft" desktop='^10' focus=off
tlminecraft="ru-turikhay-tlauncher-bootstrap-Bootstrap"
bspc rule -a "$tlminecraft" desktop='^10' focus=off
bspc rule -a "pyrogenesis" desktop='^10' focus=off
bspc rule -a "RLCraft" desktop='^10' focus=off
