#!/usr/bin/env sh

# Description: create http-server on localip:50500 with current pwd location
#
# Shell: POSIX compliant
# Author: Darukutsu
#

port=50500
ip=$(ip addr | grep 192.168 | sed "s/\/.*//;s/inet//;s/ //g")

qrencode -m 2 -t utf8 <<< "http://$ip:$port"

simple-http-server --ip $ip -p $port "$(pwd)"
