#!/usr/bin/env sh

#set -x
# Description: hide OR make visible snapshot .zfs dir for chosen dataset
#
# Shell: POSIX compliant
# Author: Darukutsu
#
header=$(zfs get snapdir | head -n1 | xargs -d"\n" printf "NTH %s")

choice=$(zfs get -H -t filesystem snapdir | awk -F'\t' '{
width = 50;
printf("%-3d %-*s %-10s %-10s\n",
NR, width, $1, $3, $4)}' | fzf --tac --header="$header")

# TODO: according to liking maybe come up with variable width or max width
#width = (length($1) > 25) ? 50 : 25;

path_to_dataset=$(echo "$choice" | tr -s " " | cut -d" " -f2)
snapdir_value=$(echo "$choice" | tr -s " " | cut -d" " -f3)

if [ "$snapdir_value" = hidden ]; then
  snapdir_value=visible
else
  snapdir_value=hidden
fi

sudo zfs set snapdir="$snapdir_value" "$path_to_dataset"
