# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
vars:
  #display: nice_view_adapter dongle_display_view_pro_micro
  keymap-drawer: true
  # These maybe should be generated, use ~ as $HOME replacement
  keymap-drawer-conf: ~/.config/zmk/config/keymap-drawer-conf.yaml
  keymap: ~/.config/zmk/config/corne.keymap
  keymap-yaml: ~/.config/zmk/config/corne.yaml
  svg-out: ~/.config/zmk/config/pics/corne.keymap.svg

include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter dongle_display_view_pro_micro
    #shield: corne_left nice_view_adapter nice_view
    #cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: corne_right
    #cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: seeeduino_xiao_ble
    shield: corne_dongle_xiao nice_view_adapter dongle_display_view_seeeduino_xiao_ble
    #shield: nrf52840_dongle nice_view_adapter dongle_display_view_seeeduino_xiao_ble
  #- board: nrfmicro_11
  #  shield: corne_dongle_pro_micro
  #  #shield: nrf52840_dongle
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nrfmicro_11
    shield: settings_reset
