# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
vars:
  # when specified here its understood as global for everykeyboard
  keymap-drawer: true
  keymap-drawer-conf: ~/.config/zmk/config/keymap-drawer-conf.yaml

include:
  - board: nice_nano_v2
    #shield: corne_left nice_view_adapter dongle_display_view_seeeduino_xiao_ble
    #shield: corne_left nice_view_adapter dongle_display_view_pro_micro
    #shield: corne_left nice_view_adapter nrf52840_dongle_display
    shield: corne_left
    #shield: corne_left nice_view_adapter nice_view
    # these break building with dongle for because wpm and other things aren't recorded on peripheral
    # use without display for now until implemented
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

    # These maybe should be generated, use ~ as $HOME replacement
    keymap: ~/.config/zmk/config/corne.keymap
    keymap-yaml: ~/.config/zmk/config/corne/corne.yaml
    svg-out: ~/.config/zmk/config/corne/pics/corne.keymap.svg
  - board: nice_nano_v2
    shield: corne_right
  - board: seeeduino_xiao_ble
    #shield: corne_dongle_xiao nice_view_adapter dongle_display_view_seeeduino_xiao_ble
    #shield: corne_dongle_pro_micro
    shield: nrf52840_dongle
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nrfmicro_11
    shield: settings_reset
  - board: nice_nano
    shield: unix60
