#Section "Device"
#    Identifier "NvidiaDevice"
#    Driver "nvidia"
#    Option "AllowEmptyInitialConfiguration" "true"
#EndSection


## OLD OPENGL HAS ITS QUIRKS KITTY WOULDN"T WORK
Section "Files"
    ModulePath "/usr/lib/xorg/modules"
EndSection

Section "Module"
    Load "glx"
    #Disable "dri"
EndSection
