layout: {zmk_keyboard: corne}
layers:
  COL:
  - $$phosphor:regular/arrows-left-right$$ Tab
  - Q
  - W
  - F
  - P
  - B
  - J
  - L
  - U
  - Y
  - SEMI
  - $$phosphor:regular/backspace$$
  - ESC
  - A
  - R
  - S
  - T
  - G
  - M
  - N
  - E
  - I
  - O
  - SQT
  - $$phosphor:regular/arrow-fat-lines-up$$
  - {t: Z, h: LGUI}
  - X
  - C
  - D
  - V
  - K
  - H
  - COMMA
  - DOT
  - {t: FSLH, h: LGUI}
  - {t: '$$phosphor:regular/key-return$$ Ret', h: RSHIFT}
  - {t: SK, h: LGUI}
  - {t: LBKT, h: VIM}
  - {t: '$$mdi:keyboard-space$$ Spc', h: LALT}
  - $$mdi:infinity$$ Meh
  - {t: RBKT, h: PROG}
  - $$phosphor:regular/repeat$$ Repeat
  COLZY:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Z
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: Y, h: LGUI}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  QWERTY:
  - $$phosphor:regular/arrows-left-right$$ Tab
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - $$phosphor:regular/backspace$$
  - LSHFT
  - A
  - S
  - D
  - F
  - G
  - H
  - J
  - K
  - L
  - SEMI
  - SQT
  - LCTRL
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - COMMA
  - DOT
  - FSLH
  - {t: '$$phosphor:regular/key-return$$ Ret', h: RSHIFT}
  - ESC
  - LALT
  - $$mdi:keyboard-space$$ Spc
  - {t: LBKT, h: VIM}
  - {t: RBKT, h: PROG}
  - RALT
  GAM1:
  - $$phosphor:regular/arrows-left-right$$ Tab
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - $$phosphor:regular/backspace$$
  - LSHFT
  - A
  - S
  - D
  - F
  - G
  - H
  - J
  - K
  - L
  - SEMI
  - SQT
  - LCTRL
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - COMMA
  - DOT
  - FSLH
  - $$phosphor:regular/key-return$$ Ret
  - LALT
  - {t: ESC, h: GAM2}
  - $$mdi:keyboard-space$$ Spc
  - {t: LBKT, h: VIM}
  - {t: RBKT, h: PROG}
  - RALT
  GAM2:
  - {t: GAM3, h: toggle}
  - '1'
  - {t: ▽, type: trans}
  - '2'
  - '3'
  - '4'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: GAM4, h: toggle}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '5'
  - '6'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ESC
  - '7'
  - '8'
  - '9'
  - '0'
  - EQUAL
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  GAM3:
  - {t: GAM3, h: toggle}
  - Y
  - U
  - I
  - O
  - P
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - H
  - J
  - K
  - L
  - SEMI
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - N
  - M
  - COMMA
  - DOT
  - FSLH
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  GAM4:
  - {t: ▽, type: trans}
  - EXCL
  - AT
  - HASH
  - DLLR
  - PRCNT
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: GAM4, h: toggle}
  - CARET
  - AMPS
  - ASTRK
  - LPAR
  - RPAR
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '7'
  - '8'
  - '9'
  - '0'
  - EQUAL
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  VIM:
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - F7
  - F8
  - F9
  - F10
  - F11
  - F12
  - ESC
  - INS
  - PSCRN
  - +PSCRN
  - PG DN
  - PG UP
  - $$phosphor:regular/arrow-left$$ Left
  - $$phosphor:regular/arrow-down$$ Down
  - $$phosphor:regular/arrow-up$$ Up
  - $$phosphor:regular/arrow-right$$ Right
  - $$phosphor:regular/caret-line-up$$ Home
  - $$phosphor:regular/caret-line-down$$ End
  - $$phosphor:regular/arrow-fat-lines-up$$
  - $$phosphor:regular/play-pause$$
  - $$phosphor:regular/speaker-slash$$
  - $$phosphor:regular/speaker-low$$
  - $$phosphor:regular/speaker-high$$
  - PG UP
  - ''
  - $$phosphor:regular/skip-forward$$
  - $$phosphor:regular/skip-back$$
  - $$phosphor:regular/sun$$
  - $$phosphor:regular/sun-dim$$
  - ''
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: MOUSE, h: toggle}
  - {t: SET, h: sticky}
  PROG:
  - GRAVE
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - MINUS
  - ESC
  - EXCL
  - AT
  - HASH
  - DLLR
  - PRCNT
  - CARET
  - AMPS
  - ASTRK
  - LPAR
  - RPAR
  - EQUAL
  - $$phosphor:regular/arrow-fat-lines-up$$
  - {t: F20, h: LGUI}
  - F21
  - F22
  - F23
  - F24
  - ''
  - COMMA
  - DOT
  - LBKT
  - {t: RBKT, h: LGUI}
  - BSLH
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - RCTL
  MOUSE:
  - {t: MOUSE, h: toggle}
  - ''
  - ''
  - {t: '$$phosphor:regular/mouse$$', h: '$$phosphor:regular/arrow-up$$'}
  - ''
  - ''
  - {t: '$$phosphor:regular/mouse-scroll$$', h: '$$phosphor:regular/arrow-down$$'}
  - {t: '$$phosphor:regular/mouse-scroll$$', h: '$$phosphor:regular/arrow-left$$'}
  - ''
  - ''
  - ''
  - ''
  - ESC
  - ''
  - {t: '$$phosphor:regular/mouse$$', h: '$$phosphor:regular/arrow-left$$'}
  - {t: '$$phosphor:regular/mouse$$', h: '$$phosphor:regular/arrow-down$$'}
  - {t: '$$phosphor:regular/mouse$$', h: '$$phosphor:regular/arrow-right$$'}
  - ''
  - {t: '$$phosphor:regular/mouse-scroll$$', h: '$$phosphor:regular/arrow-left$$'}
  - {t: '$$phosphor:regular/mouse-scroll$$', h: '$$phosphor:regular/arrow-down$$'}
  - {t: '$$phosphor:regular/mouse-scroll$$', h: '$$phosphor:regular/arrow-up$$'}
  - {t: '$$phosphor:regular/mouse-scroll$$', h: '$$phosphor:regular/arrow-right$$'}
  - ''
  - ''
  - LCTRL
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: '$$phosphor:regular/mouse-scroll$$', h: '$$phosphor:regular/arrow-up$$'}
  - {t: '$$phosphor:regular/mouse-scroll$$', h: '$$phosphor:regular/arrow-right$$'}
  - ''
  - ''
  - ''
  - {t: '$$phosphor:regular/key-return$$ Ret', h: RSHIFT}
  - ''
  - ''
  - $$phosphor:regular/mouse-left-click$$
  - $$phosphor:regular/mouse-right-click$$
  - $$phosphor:regular/mouse-scroll$$
  - ''
  SK:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ľ/Ľ
  - ú/Ú
  - ý/Ý
  - ä/Ä
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - á/Á
  - ŕ/Ŕ
  - š/Š
  - ť/Ť
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ň/Ň
  - é/É
  - í/Í
  - ó/Ó
  - ô/Ô
  - {t: ▽, type: trans}
  - ž/Ž
  - {t: ▽, type: trans}
  - č/Č
  - ď/Ď
  - {t: ▽, type: trans}
  - €
  - £
  - ¥
  - ₹
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  NUMPAD:
  - {t: NUMPAD, h: toggle}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - LNLCK
  - KP 7
  - KP 8
  - KP 9
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - KP 4
  - KP 5
  - KP 6
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - KP 1
  - KP 2
  - KP 3
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - KP 0
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  SET:
  - ''
  - ''
  - {t: NUMPAD, h: toggle}
  - {t: QWERTY, h: toggle}
  - {t: GAM1, h: toggle}
  - {t: COLZY, h: toggle}
  - OUT TOG
  - ''
  - ''
  - ''
  - ''
  - ''
  - BT CLR
  - {t: '$$phosphor:regular/bluetooth$$', h: '0'}
  - {t: '$$phosphor:regular/bluetooth$$', h: '1'}
  - {t: '$$phosphor:regular/bluetooth$$', h: '2'}
  - {t: '$$phosphor:regular/bluetooth$$', h: '3'}
  - {t: '$$phosphor:regular/bluetooth$$', h: '4'}
  - {t: '$$phosphor:regular/bluetooth-slash$$', h: '0'}
  - {t: '$$phosphor:regular/bluetooth-slash$$', h: '1'}
  - {t: '$$phosphor:regular/bluetooth-slash$$', h: '2'}
  - {t: '$$phosphor:regular/bluetooth-slash$$', h: '3'}
  - {t: '$$phosphor:regular/bluetooth-slash$$', h: '4'}
  - PWR
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '&soft_off'
  - ''
  - {type: held}
  - ''
  - ''
  - ''
  - {type: held}
