layout: {qmk_keyboard: corne_rotated, layout_name: LAYOUT_split_3x6_3}
layers:
  default:
  - TAB
  - Q
  - W
  - F
  - P
  - B
  - J
  - L
  - U
  - Y
  - ;
  - {t: BACKSPACE, s: DELETE}
  - ESC
  - A
  - R
  - S
  - T
  - G
  - M
  - N
  - E
  - I
  - O
  - ''''
  - '&shift_caps'
  - {t: Z, h: LGUI}
  - X
  - C
  - D
  - V
  - K
  - H
  - ','
  - .
  - {t: /, h: LGUI}
  - {t: RET, h: RSHIFT}
  - {t: slovak, h: LGUI}
  - {t: '[', h: vim}
  - {t: SPACE, h: LALT}
  - '&td_cmeh'
  - {t: ']', h: programming}
  - '&key_repeat'
  colemak_qwertz:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Z
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: Y, h: LGUI}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  qwerty:
  - TAB
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - {t: BACKSPACE, s: DELETE}
  - LSHFT
  - A
  - S
  - D
  - F
  - G
  - H
  - J
  - K
  - L
  - ;
  - ''''
  - LCTRL
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - {t: RET, h: RSHIFT}
  - ESC
  - LALT
  - SPACE
  - {t: '[', h: vim}
  - {t: ']', h: programming}
  - RALT
  gaming:
  - TAB
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - {t: BACKSPACE, s: DELETE}
  - LSHFT
  - A
  - S
  - D
  - F
  - G
  - H
  - J
  - K
  - L
  - ;
  - ''''
  - LCTRL
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - RET
  - LALT
  - {t: ESC, h: gaming2}
  - SPACE
  - {t: '[', h: vim}
  - {t: ']', h: programming}
  - RALT
  gaming2:
  - {t: gaming3, h: toggle}
  - '1'
  - {t: ▽, type: trans}
  - '2'
  - '3'
  - '4'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: gaming4, h: toggle}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '5'
  - '6'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ESC
  - '7'
  - '8'
  - '9'
  - '0'
  - '='
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  gaming3:
  - {t: gaming3, h: toggle}
  - Y
  - U
  - I
  - O
  - P
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - H
  - J
  - K
  - L
  - ;
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - N
  - M
  - ','
  - .
  - /
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  gaming4:
  - {t: ▽, type: trans}
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: gaming4, h: toggle}
  - ^
  - '&'
  - KP MULTIPLY
  - (
  - )
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '7'
  - '8'
  - '9'
  - '0'
  - '='
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  vim:
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - F7
  - F8
  - F9
  - F10
  - F11
  - F12
  - ESC
  - INS
  - PSCRN
  - ''
  - PG DN
  - PG UP
  - LEFT
  - DOWN
  - UP
  - RIGHT
  - HOME
  - END
  - '&shift_caps'
  - PP
  - MUTE
  - VOL DN
  - VOL UP
  - PG UP
  - ''
  - NEXT
  - PREV
  - BRI UP
  - BRI DN
  - ''
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: mouse, h: toggle}
  - {t: settings, h: sticky}
  programming:
  - '`'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - '-'
  - ESC
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - ^
  - '&'
  - KP MULTIPLY
  - (
  - )
  - '='
  - '&shift_caps'
  - {t: F20, h: LGUI}
  - F21
  - F22
  - F23
  - F24
  - ''
  - ','
  - .
  - '['
  - {t: ']', h: LGUI}
  - \
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - RCTL
  mouse:
  - {t: mouse, h: toggle}
  - ''
  - ''
  - '&mmv MOVE_UP'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ESC
  - ''
  - '&mmv MOVE_LEFT'
  - '&mmv MOVE_DOWN'
  - '&mmv MOVE_RIGHT'
  - ''
  - '&msc SCRL_LEFT'
  - '&msc SCRL_DOWN'
  - '&msc SCRL_UP'
  - '&msc SCRL_RIGHT'
  - ''
  - ''
  - LCTRL
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: RET, h: RSHIFT}
  - ''
  - ''
  - '&mkp MB1'
  - '&mkp MB2'
  - '&mkp MB3'
  - ''
  slovak:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: '&sk_lc_lower', s: '&sk_lc_upper'}
  - {t: '&sk_ua_lower', s: '&sk_ua_upper'}
  - {t: '&sk_ya_lower', s: '&sk_ya_upper'}
  - {t: '&sk_ad_lower', s: '&sk_ad_upper'}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: '&sk_aa_lower', s: '&sk_aa_upper'}
  - {t: '&sk_ra_lower', s: '&sk_ra_upper'}
  - {t: '&sk_sc_lower', s: '&sk_sc_upper'}
  - {t: '&sk_tc_lower', s: '&sk_tc_upper'}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: '&sk_nc_lower', s: '&sk_nc_upper'}
  - {t: '&sk_ea_lower', s: '&sk_ea_upper'}
  - {t: '&sk_ia_lower', s: '&sk_ia_upper'}
  - {t: '&sk_oa_lower', s: '&sk_oa_upper'}
  - {t: '&sk_ox_lower', s: '&sk_ox_upper'}
  - {t: ▽, type: trans}
  - {t: '&sk_zc_lower', s: '&sk_zc_upper'}
  - {t: ▽, type: trans}
  - {t: '&sk_cc_lower', s: '&sk_cc_upper'}
  - {t: '&sk_dc_lower', s: '&sk_dc_upper'}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  numpad:
  - {t: numpad, h: toggle}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - LNLCK
  - KP 7
  - KP 8
  - KP 9
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - KP 4
  - KP 5
  - KP 6
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - KP 1
  - KP 2
  - KP 3
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - KP 0
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  settings:
  - ''
  - ''
  - {t: numpad, h: toggle}
  - {t: qwerty, h: toggle}
  - {t: gaming, h: toggle}
  - {t: colemak_qwertz, h: toggle}
  - OUT TOG
  - ''
  - ''
  - ''
  - ''
  - PWR
  - BT CLR
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: BT, h: '3'}
  - {t: BT, h: '4'}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '&soft_off'
  - ''
  - {type: held}
  - ''
  - ''
  - ''
  - {type: held}
