layout: {qmk_keyboard: corne_rotated, qmk_layout: LAYOUT_split_3x6_3}
layers:
  default:
  - TAB
  - Q
  - W
  - F
  - P
  - B
  - J
  - L
  - U
  - Y
  - ;
  - {t: BACKSPACE, s: DELETE}
  - ESC
  - A
  - R
  - S
  - T
  - G
  - M
  - N
  - E
  - I
  - O
  - ''''
  - '&shift_caps'
  - {t: Z, h: LGUI}
  - X
  - C
  - D
  - V
  - K
  - H
  - ','
  - .
  - {t: /, h: LGUI}
  - {t: RET, h: RSHIFT}
  - '&td_gui'
  - {t: '[', h: vim}
  - {t: SPACE, h: LALT}
  - '&td_cmeh'
  - {t: ']', h: programming}
  - '&key_repeat'
  colemak_qwertz:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Z
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: Y, h: LGUI}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  qwerty:
  - TAB
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - {t: BACKSPACE, s: DELETE}
  - LSHFT
  - A
  - S
  - D
  - F
  - G
  - H
  - J
  - K
  - L
  - ;
  - ''''
  - LCTRL
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - {t: RET, h: RSHIFT}
  - ESC
  - LALT
  - SPACE
  - {t: '[', h: vim}
  - {t: ']', h: programming}
  - RALT
  gaming:
  - TAB
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - {t: BACKSPACE, s: DELETE}
  - LSHFT
  - A
  - S
  - D
  - F
  - G
  - H
  - J
  - K
  - L
  - ;
  - ''''
  - LCTRL
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - {t: RET, h: RSHIFT}
  - ESC
  - {t: LALT, h: gaming2}
  - SPACE
  - {t: '[', h: vim}
  - {t: ']', h: programming}
  - RALT
  gaming2:
  - {t: ▽, type: trans}
  - '1'
  - {t: ▽, type: trans}
  - '2'
  - '3'
  - '4'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '5'
  - '6'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  vim:
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - F7
  - F8
  - F9
  - F10
  - F11
  - F12
  - ESC
  - INS
  - PSCRN
  - ''
  - PG DN
  - PG UP
  - LEFT
  - DOWN
  - UP
  - RIGHT
  - HOME
  - END
  - '&shift_caps'
  - PP
  - MUTE
  - VOL DN
  - VOL UP
  - PG UP
  - ''
  - NEXT
  - PREV
  - BRI UP
  - BRI DN
  - ''
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: mouse, h: toggle}
  - {t: settings, h: sticky}
  programming:
  - '`'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - '-'
  - ESC
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - ^
  - '&'
  - KP MULTIPLY
  - (
  - )
  - '='
  - '&shift_caps'
  - {t: F20, h: LGUI}
  - F21
  - F22
  - F23
  - F24
  - ''
  - ','
  - .
  - '['
  - {t: ']', h: LGUI}
  - \
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - RCTL
  mouse:
  - {t: mouse, h: toggle}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  slovak:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  settings:
  - ''
  - ''
  - ''
  - {t: qwerty, h: toggle}
  - {t: gaming, h: toggle}
  - {t: colemak_qwertz, h: toggle}
  - OUT TOG
  - ''
  - ''
  - ''
  - ''
  - PWR
  - BT CLR
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: BT, h: '3'}
  - {t: BT, h: '4'}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  - ''
  - {type: held}
