draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: false
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  svg_extra_style: ""
  footer_text: Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
  use_local_cache: true
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map: {
      ## FreeAwesome
      #"&mmv MODE_LEFT":
      #  { t: $$fa:solid/computer-mouse$$, h: $$fa:solid/arrow-left$$ },
      #"&mmv MODE_DOWN":
      #  { t: $$fa:solid/computer-mouse$$, h: $$fa:solid/arrow-down$$ },
      #"&mmv MODE_UP":
      #  { t: $$fa:solid/computer-mouse$$, h: $$fa:solid/arrow-up$$ },
      #"&mmv MODE_RIGHT":
      #  { t: $$fa:solid/computer-mouse$$, h: $$fa:solid/arrow-right$$ },
      #"&msc SCRL_LEFT":
      #  {
      #    t: $$fa:solid/computer-mouse-scrollwheel$$,
      #    h: $$fa:solid/arrow-left$$,
      #  },
      #"&msc SCRL_DOWN":
      #  {
      #    t: $$fa:solid/computer-mouse-scrollwheel$$,
      #    h: $$fa:solid/arrow-down$$,
      #  },
      #"&msc SCRL_UP":
      #  {
      #    t: $$fa:solid/computer-mouse-scrollwheel$$,
      #    h: $$fa:solid/arrow-up$$,
      #  },
      #"&msc SCRL_RIGHT":
      #  {
      #    t: $$fa:solid/computer-mouse-scrollwheel$$,
      #    h: $$fa:solid/arrow-right$$,
      #  },
      ## ProAwesome
      #"&mmv MODE_LEFT":
      #  { t: $$fa:solid/computer-mouse$$, h: $$fa:solid/left$$ },
      #"&mmv MODE_DOWN":
      #  { t: $$fa:solid/computer-mouse$$, h: $$fa:solid/down$$ },
      #"&mmv MODE_UP": { t: $$fa:solid/computer-mouse$$, h: $$fa:solid/up$$ },
      #"&mmv MODE_RIGHT":
      #  { t: $$fa:solid/computer-mouse$$, h: $$fa:solid/right$$ },
      #"&msc SCRL_LEFT":
      #  { t: $$fa:solid/computer-mouse-scrollwheel$$, h: $$fa:solid/left$$ },
      #"&msc SCRL_DOWN":
      #  { t: $$fa:solid/computer-mouse-scrollwheel$$, h: $$fa:solid/down$$ },
      #"&msc SCRL_UP":
      #  { t: $$fa:solid/computer-mouse-scrollwheel$$, h: $$fa:solid/up$$ },
      #"&msc SCRL_RIGHT":
      #  { t: $$fa:solid/computer-mouse-scrollwheel$$, h: $$fa:solid/right$$ },

      ## Phosphor
      "&mmv MODE_LEFT":
        { t: $$phosphor:regular/mouse$$, h: $$phosphor:regular/arrow-left$$ },
      "&mmv MODE_DOWN":
        { t: $$phosphor:regular/mouse$$, h: $$phosphor:regular/arrow-down$$ },
      "&mmv MODE_UP":
        { t: $$phosphor:regular/mouse$$, h: $$phosphor:regular/arrow-up$$ },
      "&mmv MODE_RIGHT":
        { t: $$phosphor:regular/mouse$$, h: $$phosphor:regular/arrow-right$$ },
      "&msc SCRL_LEFT":
        {
          t: $$phosphor:regular/mouse-scroll$$,
          h: $$phosphor:regular/arrow-left$$,
        },
      "&msc SCRL_DOWN":
        {
          t: $$phosphor:regular/mouse-scroll$$,
          h: $$phosphor:regular/arrow-down$$,
        },
      "&msc SCRL_UP":
        {
          t: $$phosphor:regular/mouse-scroll$$,
          h: $$phosphor:regular/arrow-up$$,
        },
      "&msc SCRL_RIGHT":
        {
          t: $$phosphor:regular/mouse-scroll$$,
          h: $$phosphor:regular/arrow-right$$,
        },

      ## Phosphor
      "$mkp MB1": "$$phosphor:regular/mouse-left-click$$",
      "$mkp MB2": "$$phosphor:regular/mouse-right-click$$",
      "$mkp MB3": "$$phosphor:regular/mouse-scroll$$",
      "&soft-off": "$$phosphor:regular/keyboard-down$$",
      "&shift_caps": "$$phosphor:regular/arrow-fat-lines-up$$",
      "&key_repeat": "$$phosphor:regular/repeat$$",
      "&bspc_del": "$$phosphor:regular/backspace$$",

      ## FontAwesome
      #"$mkp MB1": "$$fa:solid/computer-mouse-button-left$$",
      #"$mkp MB2": "$$fa:solid/computer-mouse-button-right$$",
      #"$mkp MB3": "$$fa:solid/computer-mouse-scrollwheel$$",
      #"&soft-off": "$$fa:solid/keyboard-down$$",
      ##"&shift_caps": "SftCpsW",
      #"&shift_caps": "$$fa:solid/arrow-up-from-bracket$$",
      ##"&shift_caps": "$$fa:solid/lock-a$$",
      #"&key_repeat": "$$fa:solid/fa-repeat$$",
      
  
      "&sk_ad": "√§/√Ñ",
      "&sk_aa": "√°/√Å",
      "&sk_ea": "√©/√â",
      "&sk_ia": "√≠/√ç",
      "&sk_ua": "√∫/√ö",
      "&sk_oa": "√≥/√ì",
      "&sk_ox": "√¥/√î",
      "&sk_ya": "√Ω/√ù",
      "&sk_dc": "ƒè/ƒé",
      "&sk_tc": "≈•/≈§",
      "&sk_nc": "≈à/≈á",
      "&sk_lc": "ƒæ/ƒΩ",
      "&sk_cc": "ƒç/ƒå",
      "&sk_zc": "≈æ/≈Ω",
      "&sk_sc": "≈°/≈†",
      "&sk_ra": "≈ï/≈î",
      "&curr_dollar": "$",
      "&curr_cent": "¬¢",
      "&curr_pound": "¬£",
      "&curr_currency": "¬§",
      "&curr_yen": "¬•",
      "&curr_armenian_dram": "÷è",
      "&curr_afghani_dram": "ÿã",
      "&curr_nko_dorome": "ﬂæ",
      "&curr_bengali_rupee1": "‡ß≤",
      "&curr_bengali_rupee2": "‡ß≥",
      "&curr_bengali_ganda": "‡ßª",
      "&curr_gujarati_rupee": "‡´±",
      "&curr_tamil_rupee": "‡Øπ",
      "&curr_thai_baht": "‡∏ø",
      "&curr_khmer_riel": "·üõ",
      "&curr_colon": "‚Ç°",
      "&curr_cruzeiro": "‚Ç¢",
      "&curr_french_franc": "‚Ç£",
      "&curr_lira": "‚Ç£",
      "&curr_mill": "‚Ç•",
      "&curr_naira": "‚Ç¶",
      "&curr_peseta": "‚Çß",
      "&curr_legacy_rupee": "‚Ç®",
      "&curr_won": "‚Ç©",
      "&curr_new_sheqel": "‚Ç™",
      "&curr_dong": "‚Ç´",
      "&curr_euro": "‚Ç¨",
      "&curr_kip": "‚Ç≠",
      "&curr_tugrik": "‚ÇÆ",
      "&curr_drachma": "‚ÇØ",
      "&curr_german_penny": "‚Ç∞",
      "&curr_peso": "‚Ç±",
      "&curr_guarani": "‚Ç≤",
      "&curr_austral": "‚Ç≥",
      "&curr_hryvnia": "‚Ç¥",
      "&curr_cedi": "‚Çµ",
      "&curr_livre_tournois": "‚Ç∂",
      "&curr_spesmilo": "‚Ç∑",
      "&curr_tenge": "‚Ç∏",
      "&curr_indian_rupee": "‚Çπ",
      "&curr_turkish_lira": "‚Ç∫",
      "&curr_nordic_mark": "‚Çª",
      "&curr_manat": "‚Çº",
      "&curr_ruble": "‚ÇΩ",
      "&curr_lari": "‚Çæ",
      "&curr_bitcoin": "‚Çø",
      "&curr_som": "‚ÉÄ",
      "&curr_north_indic_rupee": "Í†∏",
      "&curr_rial": "Ô∑º",
      "&curr_wancho_ngun": "ûãø",
      "&super_pscrn": "+PSCRN",
    }
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ‚ñΩ
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    #ctrl: "$$phosphor:regular/caret-up$$"
    #alt: "$$phosphor:regular/escalator-up$$"
    #shift: "$$phosphor:regular/escalator-up$$"
    #gui: "$$fa:brands/linux$$"
    left_ctrl: Ctl
    right_ctrl: RCtl
    left_shift: Sft
    right_shift: RSft
    left_alt: Alt
    right_alt: AGr
    left_gui: LGui
    right_gui: RGui
    keycode_combiner: "{mods}+ {key}"
    mod_combiner: "{mod_1}+{mod_2}"
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_remove_keycode_prefix:
    - KC_
  qmk_keycode_map:
    XXXXXXX: ""
    "NO": ""
    MINUS: "-"
    MINS: "-"
    EQUAL: "="
    EQL: "="
    LEFT_BRACKET: "["
    LBRC: "["
    RIGHT_BRACKET: "]"
    RBRC: "]"
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: "#"
    NUHS: "#"
    SEMICOLON: ;
    SCLN: ;
    QUOTE: "'"
    QUOT: "'"
    GRAVE: "`"
    GRV: "`"
    COMMA: ","
    COMM: ","
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: "~"
    TILD: "~"
    EXCLAIM: "!"
    EXLM: "!"
    AT: "@"
    HASH: "#"
    DOLLAR: $
    DLR: $
    PERCENT: "%"
    PERC: "%"
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: "&"
    AMPR: "&"
    ASTERISK: "*"
    ASTR: "*"
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: "{"
    LCBR: "{"
    RIGHT_CURLY_BRACE: "}"
    RCBR: "}"
    PIPE: "|"
    COLON: ":"
    COLN: ":"
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: ">"
    RABK: ">"
    GT: ">"
    QUESTION: "?"
    QUEST: "?"
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: "="
    PLUS: +
    MINUS: "-"
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: \
    BSLH: \
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON: ;
    SEMI: ;
    COLON: ":"
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ","
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT: "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"
    #CTRL: "$$phosphor:regular/caret-up$$"
    #ALT: "$$phosphor:regular/escalator-up$$"
    #CTRL: "$$fa:solid/angle-up$$"
    #DELETE: "$$fa:solid/delete-left$$"

  zmk_combos: {}
  zmk_preamble: "#define KEYMAP_DRAWER"
  zmk_additional_includes: ["zmk-helpers/include"]
  layout:
    { dts_layout: ~/.config/zmk/zmk/app/dts/layouts/foostan/corne/6column.dtsi }
