#!/bin/sh
# See the river(1), riverctl(1), and rivertile(1) man pages for complete documentation.

# TODO: source this to environment
export XDG_CURRENT_DESKTOP=river
export XDG_CURRENT_SESSION=wayland
export OPACITY_VALUE=1.0
export _JAVA_AWT_WM_NONREPARENTING=1
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export SXHKD_MODE_FILE="$HOME/.config/sxhkd/zscroll-polybar"
#export WINIT_UNIX_BACKEND=x11

# The scratchpad will live on an unused tag. Which tags are used depends on your
# config, but rivers default uses the first 9 tags.
export RIVER_SCRATCH_TAG1=$((1 << 30))
export RIVER_SCRATCH_TAG2=$((1 << 29))
export RIVER_SCRATCH_TAG3=$((1 << 28))

echo left >"$XDG_CONFIG_HOME"/river/.current_layout
echo 1 >"$XDG_CONFIG_HOME"/river/.current_tag

xrdb -load "$XDG_CONFIG_HOME/X11/xresources"

# Monitor config
#if [ $( | wc -l) -gt 1 ]; then
kanshi &
#riverctl rule-add -app-id '*' output DP-4
#wlr-randr --output eDP-1 --off
#fi

# Set background and border color
#riverctl background-color 0x002b36
killall "swww-daemon"
swww-daemon &
wallpaper=$(ls ~/Pictures/wallpapers/arch1* | shuf -n 1)
swww img "$wallpaper" &

killall "waybar"
waybar &

#
# NOTE: keymaps
#
# fuck wayland keybinds are awful
#killall "swhks"
#swhks &
#killall "swhkd"
#pkexec swhkd &
. "$XDG_CONFIG_HOME"/river/keymaps

#
# NOTE: Rules
#
. "$XDG_CONFIG_HOME"/river/rules

#
# NOTE: Services
#
. "$XDG_CONFIG_HOME"/bspwm/services

riverctl border-width 3
riverctl border-color-focused 0x6181ff
riverctl border-color-unfocused 0x586e75
riverctl set-cursor-warp on-focus-change
riverctl hide-cursor timeout 2000
riverctl hide-cursor when-typing enabled
riverctl set-repeat 30 300
riverctl input pointer-1133-16493-Logitech_M705 scroll-factor 0.8
riverctl input pointer-1133-16493-Logitech_M705 pointer-accell -0.1

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 -main-ratio 0.5 &

# Execute scratchpad after rules are sourced
killall kitty
#killall -r '*combo-kitty*'
#killall -r '*float-kitty*'

kitty --class="float-kitty1" &
kitty --class="float-kitty2" &

kitty --hold --class="combo-kitty1" pulsemixer &
kitty --hold --class="combo-kitty2" calcure &
kitty --hold --class="combo-kitty3" pacseek -u &
kitty --hold --class="combo-kitty4" nf &
