
unused = "#79e11a"

[tokyo]
  gray1 = "#464752"
  gray2 = "#565761"
  gray3 = "#b6b6b2"
  gray4 = "#ccccc7"
  black = "#24283b"
  blue = "#6272a4"
  cyan = "#364a82"
  green = "#50fa7b"
  magenta = "#7aa2f7"
  orange = "#ffb86c"
  purple = "#bd93f9"
  red = "#f7768e"
  white = "#c0caf5"
  yellow = "#73daca"

[dark]
  button = ["tokyo.black","tokyo.gray3"]
  button-focus = ["tokyo.black","tokyo.magenta"]
  button-selected = ["tokyo.white","tokyo.gray3"]
  cmdline = ["tokyo.black","tokyo.yellow"]
  cmdline-button = ["tokyo.yellow","tokyo.black"]
  cmdline-border = ["tokyo.black","tokyo.yellow"]
  copy-mode = ["tokyo.black","tokyo.yellow"]
  copy-mode-alt = ["tokyo.yellow","tokyo.black"]
  copy-mode-label = ["tokyo.white","tokyo.red"]
  current-capture = ["tokyo.white","themes.unused"]
  dialog = ["tokyo.black","tokyo.yellow"]
  dialog-button = ["tokyo.yellow","tokyo.black"]
  default = ["tokyo.white","tokyo.black"]
  filter-empty = ["tokyo.black","tokyo.cyan"]
  filter-intermediate = ["tokyo.black","tokyo.orange"]
  filter-invalid = ["tokyo.black","tokyo.red"]
  filter-menu = ["tokyo.white","tokyo.black"]
  filter-valid = ["tokyo.black","tokyo.green"]
  hex-byte-selected = ["tokyo.black","tokyo.purple"]
  hex-byte-unselected = ["tokyo.white","tokyo.black"]
  hex-field-selected = ["tokyo.white","tokyo.cyan"]
  hex-field-unselected = ["tokyo.black","tokyo.white"]
  hex-interval-selected = ["tokyo.white","tokyo.gray2"]
  hex-interval-unselected = ["tokyo.white","tokyo.gray1"]
  hex-layer-selected = ["tokyo.white","tokyo.gray2"]
  hex-layer-unselected = ["tokyo.white","tokyo.gray1"]
  packet-list-cell-focus = ["tokyo.white","tokyo.cyan"]
  packet-list-cell-selected = ["tokyo.white","tokyo.gray2"]
  packet-list-row-focus = ["tokyo.white","tokyo.cyan"]
  packet-list-row-selected = ["tokyo.white","tokyo.gray1"]
  packet-struct-focus = ["tokyo.white","tokyo.cyan"]
  packet-struct-selected = ["tokyo.white","tokyo.gray2"]
  progress-complete = ["tokyo.white","tokyo.purple"]
  progress-default = ["tokyo.white","tokyo.black"]
  progress-spinner = ["tokyo.yellow","tokyo.purple"]
  spinner = ["tokyo.yellow","tokyo.black"]
  stream-client = ["tokyo.black","tokyo.red"]
  stream-match = ["tokyo.black","tokyo.yellow"]
  stream-search = ["tokyo.black","tokyo.white"]
  stream-server = ["tokyo.white","tokyo.blue"]
  title = ["tokyo.red","unused"]

[light]
  button = ["tokyo.black","tokyo.white"]
  button-focus = ["tokyo.black","tokyo.purple"]
  button-selected = ["tokyo.black","tokyo.gray3"]
  cmdline = ["tokyo.black","tokyo.yellow"]
  cmdline-button = ["tokyo.yellow","tokyo.black"]
  cmdline-border = ["tokyo.black","tokyo.yellow"]
  copy-mode = ["tokyo.white","tokyo.yellow"]
  copy-mode-alt = ["tokyo.yellow","tokyo.white"]
  copy-mode-label = ["tokyo.black","tokyo.red"]
  current-capture = ["tokyo.black","unused"]
  dialog = ["tokyo.black","tokyo.yellow"]
  dialog-button = ["tokyo.yellow","tokyo.black"]
  default = ["tokyo.black","tokyo.white"]
  filter-empty = ["tokyo.black","tokyo.cyan"]
  filter-intermediate = ["tokyo.black","tokyo.orange"]
  filter-invalid = ["tokyo.black","tokyo.red"]
  filter-menu = ["tokyo.black","tokyo.white"]
  filter-valid = ["tokyo.black","tokyo.green"]
  hex-byte-selected = ["tokyo.black","tokyo.purple"]
  hex-byte-unselected = ["tokyo.black","tokyo.white"]
  hex-field-selected = ["tokyo.white","tokyo.cyan"]
  hex-field-unselected = ["tokyo.black","tokyo.gray2"]
  hex-interval-selected = ["tokyo.white","tokyo.gray2"]
  hex-interval-unselected = ["tokyo.black","tokyo.gray4"]
  hex-layer-selected = ["tokyo.white","tokyo.gray2"]
  hex-layer-unselected = ["tokyo.black","tokyo.gray4"]
  packet-list-cell-focus = ["tokyo.white","tokyo.cyan"]
  packet-list-cell-selected = ["tokyo.black","tokyo.gray3"]
  packet-list-row-focus = ["tokyo.white","tokyo.cyan"]
  packet-list-row-selected = ["tokyo.black","tokyo.gray4"]
  packet-struct-focus = ["tokyo.white","tokyo.cyan"]
  packet-struct-selected = ["tokyo.black","tokyo.gray4"]
  progress-complete = ["tokyo.white","tokyo.purple"]
  progress-default = ["tokyo.white","tokyo.black"]
  progress-spinner = ["tokyo.yellow","tokyo.black"]
  spinner = ["tokyo.yellow","tokyo.white"]
  stream-client = ["tokyo.white","tokyo.red"]
  stream-match = ["tokyo.white","tokyo.yellow"]
  stream-search = ["tokyo.white","tokyo.black"]
  stream-server = ["tokyo.white","tokyo.blue"]
  title = ["tokyo.red","unused"]
