#!/bin/sh
alias testalias="pkexec env DISPLAY=$DISPLAY  XAUTHORITY=$XAUTHORITY notify-send DISPLAY=$DISPLAY  XAUTHORITY=$XAUTHORITY"
alias a='ani-cli'
#alias a='adl -r'
alias alsa='pulsemixer'
alias abackup='mv /home/daru/Android/MI9-backup /home/daru/Android/MI9-backup.$(stat -c %w /home/daru/Android/MI9-backup/ | awk "{print $1}") && mkdir /home/daru/Android/MI9-backup/ && sudo bftpd -d'
alias cnet="netstat -lantp | grep ESTABLISHED |awk '{print $5}' | awk -F: '{print $1}' | sort -u"
#alias c='printf "\033c"'
alias c='tput reset'
alias cpic='wl-color-picker'
alias bongacam='sudo scrcpy -N --no-window --video-source camera --camera-{size=1920x1080,facing=front} --v4l2-sink /dev/video0 --capture-orientation 180'
alias cam='sudo scrcpy -N --no-window --video-source camera --camera-{size=1920x1080,facing=front} --v4l2-sink /dev/video0 --capture-orientation 180'
alias clam='freshclam && clamscan --recursive --bell'
alias clamstop='sudo systemctl stop clamav-clamonacc && sudo systemctl stop clamav-daemon'
alias clamstart='sudo systemctl start clamav-clamonacc && sudo systemctl start clamav-daemon'
alias emacs='emacs -nw'
alias find-cursor='sxcs'
alias firefox='firefox-developer-edition'
alias fr='firefox-developer-edition'
alias gpt='python3 -m revChatGPT.V3 --api_key $OPENAI_API_KEY'
#alias history='atuin history list --cmd-only'
alias ical='calcure'
alias ipadmin='echo 192.168.188.1'
alias ipglo='curl ident.me; echo'
alias iploc='ip addr | grep 192.168 | sed "s/\/.*//;s/inet//;s/ //g"'
#alias iploc='ip addr | grep 192.168 | sed "s/brd.*//;s/inet//;s/ //g"'
#alias kkey='kdeconnect -l | sed "s///" | kdeconnect -n "" -k'
alias killj='kill -9 $(jobs -p)'
alias lsp='ls /usr/bin|fzf'
alias ll='ls --color=auto -la'
alias blk='colourify lsblk -o "NAME,SIZE,FSTYPE,FSAVAIL,FSUSED,FSUSE%,MOUNTPOINTS"'
alias lapt0='xinput set-prop "AT Translated Set 2 keyboard" "Device Enabled" 0'
alias lapt1='xinput set-prop "AT Translated Set 2 keyboard" "Device Enabled" 1'
#alias mt='neomutt'
#alias nf='$XDG_CONFIG_HOME/neofetch/rand-pic.sh && neofetch'
alias ff='fastfetch --logo $(find "$XDG_CONFIG_HOME/fastfetch/pic/" -type f | shuf -n 1)'
alias ffall='fastfetch -c /usr/share/fastfetch/presets/ci.jsonc'
#alias micsend="pactl load-module module-tunnel-sink server=tcp:$(iploc):10111"
alias micsend="
pactl load-module module-native-protocol-tcp listen=$(iploc);
pactl load-module module-zeroconf-publish
"
alias micrecv="
pactl load-module module-zeroconf-discover; 
pactl load-module module-native-protocol-tcp port=$1 listen=$2 auth-anonymous=1
"
alias mov='mov-cli -s films'
#alias mirror='xrandr --output HDMI-1 --auto; mons -m'
alias mirror='mons -ma'
#alias nnn='nnn -cdHa'
#alias page='$PAGER'
alias pingg='ping google.com'
alias pc='pacseek -u'
alias rollback='downgrade'
#alias rsyn='rsync -AaPhxz --size-only'
alias rsyn='rsync -aPh --size-only'
alias shazam='$XDG_CONFIG_HOME/bash/songrec-fix.sh'
alias sk='
if [ "$XDG_SESSION_TYPE" = "x11" ]; then
  screenkey -t 1.5 --vis-shift -g 30%x60%+68%-4%
else
  wshowkeys -t 1.5 -a bottom
fi'

#alias s='kitten ssh'
alias snv='sudo nvim'
alias saj='sudo archlinux-java'
#alias songrec='songrec listen -d default'
alias s='sudo'
#alias Ss='sudo su'
alias SS='sudo systemctl'
alias SU='systemctl --user'
alias yt='yt-dlp'
alias p='poweroff'
alias r='reboot'
alias rgg='grep -rniI --color=always * -e'
alias record-fast='gpu-screen-recorder -w screen -f 60 -k h264 -c mp4 -o ~/Videos'
alias yayu='sudo pacman  -Rns $(pacman -Qdtq)'
alias yayr='yay -Rns'
alias yays='yay -Sc'
#alias yayf='sudo pacman -Rns flutter && yay flutter'
alias yayi='yay --ignore linux,linux-headers,zfs-linux'
#alias yayz='sudo pacman -Syu --nodeps'
alias yayz='yay --nodeps'
alias xdgn='xdg-ninja --skip-ok --skip-unsupported'
alias sddm-greeter='sddm-greeter --theme /usr/share/sddm/themes/sober --test-mode'
#adb connect 192.168.0.128:38345
alias scr='scrcpy --disable-screensaver -Sf'
#alias winreboot='sudo grub-reboot osprober-efi-388F-7355 && reboot'
alias winreboot='systemctl reboot --boot-loader-entry=win.conf'
alias sshk='kitty +kitten ssh'
alias https='simple-http-server --ip $(iploc) -p 50500'
alias xclip='xclip -selection clipboard'
#alias traceroute='/usr/bin/mtr'
alias qr='qrencode -m 2 -t utf8 <<< "$1"'
alias qrdecode='zbarimg'
alias qrwifi='nmcli device wifi show-password'
alias hotspot='sudo create_ap wlan0 eth0 linux aaaassss'
#alias xev2=xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }

alias urlsed='sed "s#[@/\^.$|()[*+?{}\#,&=:~]\|-\|\]#\\\&#g"'

#alias gib='git branch'
#alias gic='git commit'
#alias gich='git checkout'
#alias gis='git status'
#alias gia='git add'
