[options]
HoldPkg     = pacman glibc
Architecture = auto
Color
VerbosePkgLists
ParallelDownloads = 5
#DownloadUser = alpm
NoExtract = usr/lib/modules/*
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[lizardbyte]
SigLevel = Optional
Server = https://github.com/LizardByte/pacman-repo/releases/latest/download
